//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.05 at 03:50:32 PM EDT 
//


package com.zamir.actor_ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zamir.actor_ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zamir.actor_ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetActorByIdRequest }
     * 
     */
    public GetActorByIdRequest createGetActorByIdRequest() {
        return new GetActorByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteActorResponse }
     * 
     */
    public DeleteActorResponse createDeleteActorResponse() {
        return new DeleteActorResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link UpdateActorResponse }
     * 
     */
    public UpdateActorResponse createUpdateActorResponse() {
        return new UpdateActorResponse();
    }

    /**
     * Create an instance of {@link GetAllActorsResponse }
     * 
     */
    public GetAllActorsResponse createGetAllActorsResponse() {
        return new GetAllActorsResponse();
    }

    /**
     * Create an instance of {@link ActorInfo }
     * 
     */
    public ActorInfo createActorInfo() {
        return new ActorInfo();
    }

    /**
     * Create an instance of {@link AddActorRequest }
     * 
     */
    public AddActorRequest createAddActorRequest() {
        return new AddActorRequest();
    }

    /**
     * Create an instance of {@link UpdateActorRequest }
     * 
     */
    public UpdateActorRequest createUpdateActorRequest() {
        return new UpdateActorRequest();
    }

    /**
     * Create an instance of {@link DeleteActorRequest }
     * 
     */
    public DeleteActorRequest createDeleteActorRequest() {
        return new DeleteActorRequest();
    }

    /**
     * Create an instance of {@link AddActorResponse }
     * 
     */
    public AddActorResponse createAddActorResponse() {
        return new AddActorResponse();
    }

    /**
     * Create an instance of {@link GetAllActorsRequest }
     * 
     */
    public GetAllActorsRequest createGetAllActorsRequest() {
        return new GetAllActorsRequest();
    }

    /**
     * Create an instance of {@link GetActorByIdResponse }
     * 
     */
    public GetActorByIdResponse createGetActorByIdResponse() {
        return new GetActorByIdResponse();
    }

}
