//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.05 at 03:50:32 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zamir.com/actor-ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zamir.actor_ws;
